services:
  pocketbase-pomerium-jwt-auth:
    build: .
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./data:/pb_data
    environment:
      # Configuration environment variables
      - DEBUG=false
      - JWT_HEADER=X-Pomerium-Jwt-Assertion
      - PB_DATA_DIR=/pb_data # PocketBase data directory (optional, defaults to /pb_data)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
