services:
  pocketbase-pomerium-jwt-auth:
    build: .
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./data:/pb_data
    environment:
      # Only 2 optional environment variables!
      - DEBUG=false
      - JWT_HEADER=X-Pomerium-Jwt-Assertion
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--spider",
          "http://localhost:8090/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
